#!/bin/bash
# Copyright (c) 2009 Cloudera, inc
#
# Performs a release build

set -ex

JAVA32_HOME=${JAVA32_HOME:-$JAVA_HOME}

# Check that JVMs support the right architectures
# Passing -d with an architecture that's not supported results
# in a non-zero exit code even with -version
if ! $JAVA32_HOME/bin/java -d32 -version ; then
  echo Your jvm in $JAVA32_HOME seems like it doesnt support 32-bit mode 1>&2
  echo Please set JAVA32_HOME to point to a 32-bit JDK
  exit 1
fi

# Do the build
BIN_DIR=$(readlink -f $(dirname $0))
RELEASE_DIR=$BIN_DIR/..

# Change to cloudera/maven directory, compile, install
# (and if called from CDH nightly build, deploy) artifacts into Maven repository
cd $BIN_DIR/maven-packaging
JAVA_HOME=$JAVA32_HOME mvn -Dnot.cdh.release.build=false install $DO_MAVEN_DEPLOY


